version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: protzy-postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: protzy_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - protzy-network

  redis:
    image: redis:7
    container_name: protzy-redis
    restart: always

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command: redis-server --appendonly yes

    networks:
      - protzy-network

  minio:
    image: minio/minio:latest
    container_name: protzy-minio
    restart: always

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: protzyadmin
      MINIO_ROOT_PASSWORD: protzy@2026Storage

    command: server /data --console-address ":9001"

    volumes:
      - minio_data:/data

    networks:
      - protzy-network

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile

    container_name: protzy-backend-container
    restart: always

    ports:
      - "3000:3000"

    env_file:
      - .env

    environment:
      DATABASE_URL: "postgresql://postgres:postgres@protzy-postgres:5432/protzy_db?schema=public"

      REDIS_HOST: protzy-redis
      REDIS_PORT: 6379

      MINIO_ENDPOINT: protzy-minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: false
      MINIO_ACCESS_KEY: protzyadmin
      MINIO_SECRET_KEY: protzy@2026Storage

    depends_on:
      - postgres
      - redis
      - minio

    networks:
      - protzy-network

networks:
  protzy-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  minio_data: